[package]
name = "ploars_crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version = "0.29.0", features = ["lazy"] }
polars-ops = { version = "0.29.0", features = ["pivot"] }
